import admin from '@/lib/firebaseAdmin';
import { Configuration, OpenAIApi } from 'openai';

const db = admin.firestore();

const configuration = new Configuration({
  apiKey: process.env.OPENAI_API_KEY,
});
const openai = new OpenAIApi(configuration);

export default async function handler(req, res) {
  if (req.method === 'POST') {
    const { agentId, message, prompt } = req.body;

    // Input Validation
    if (!agentId || !message || !prompt) {
      return res.status(400).json({ error: 'Missing required fields: agentId, message, or prompt.' });
    }

    try {
      // Communicate with OpenAI
      const openaiRes = await openai.createCompletion({
        model: 'text-davinci-003',
        prompt,
        max_tokens: 150,
        temperature: 0.7,
      });

      // Extract and validate the response
      const reply = openaiRes.data.choices?.[0]?.text?.trim();
      if (!reply) {
        throw new Error('No response generated by OpenAI.');
      }

      // Log the chat to Firestore
      await db.collection('agentChats').add({
        agentId,
        userMessage: message,
        botReply: reply,
        timestamp: admin.firestore.Timestamp.now(),
      });

      // Return the reply
      res.status(200).json({ reply });
    } catch (error) {
      console.error('Error handling chat request:', error.message);

      // Handle OpenAI-specific errors
      if (error.response) {
        console.error('OpenAI Error Response:', error.response.data);
      }

      res.status(500).json({ error: 'Failed to generate a response. Please try again later.' });
    }
  } else {
    res.status(405).json({ error: 'Method not allowed.' });
  }
}
